### ISSUE TITLE
Different Experiment Setting in Different Version Paper ( Learning to Explore with Meta PG - ICML 2018 )

### ISSUE THREAD

**Issue by RchalYang** [tianbingsz/MLResearch#1]
Sorry for the disturbance. When I'm trying to reproduce the result of your work: Learning to Explore with Meta-Policy Gradient, I found that the experiment setting stated in two versions(Arxiv & PMLR) of your paper is slightly different. I'm wondering which version works better for this task? Is there any open source code I can refer to?

Sorry again for my rudeness for contacting in this way. I could not find your contact elsewhere, or could you send me an email so that we could talk about it by email? My email is ruihanyang97@gmail.com

Ruihan Yang
05/07/2019
ruihanyang97@gmail.com

**Comment by RchalYang** [comment]
Arxiv Version: https://arxiv.org/pdf/1803.05044.pdf
5.1 Experiment Setting:
For the meta-exploration policy (teacher πe), we implemented a stochastic Gaussian policy with a mean network represented with a MLP with two hidden layers (64-64), and **a log-standard-deviation variance network with a MLP with two hidden layers (64-64).**

**Comment by RchalYang** [comment]
PMLR Version: http://proceedings.mlr.press/v80/xu18d/xu18d.pdf
5.1 Experiment Setting:
For the meta-exploration policy (Meta πe), we implemented a stochastic Gaussian policy with a mean network represented with a MLP with two hidden layers (64-64), and **a log-standard-deviation variance variable.**

**Comment by tianbingsz** [comment]
Actually, we tried both versions for the variance, the results seem not too much difference. So, in the final version, we use the simplest one.
